name: ci-backend

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - starter/backend/**
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:  
          python-version: '3.10'
      # Dependencies
      - name: dependencies
        run: cd starter/backend && pip install pipenv && pipenv install
      # Run the linter.
      - name: linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:  
          python-version: '3.10'
      # Install the dependencies.
      - name: dependencies
        run: cd starter/backend && pip install pipenv && pipenv install
      # Run the tests.
      - name: test
        run: cd starter/backend/ && python test_app.py
        
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:  
          python-version: '3.10'
      # Install the dependencies.
      - name: dependencies
        run: cd starter/backend && pip install pipenv && pipenv install
      # Run the tests.
      - name: test
        run: cd starter/backend/ && python test_app.py
        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: starter/backend/.
          push: False